openapi: 3.0.3
info:
  title: "特定のヒット情報を取得"
  version: "1.0"
paths: {}
components:
  responses:
    200:
      description: |-
        ヒット情報
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/fetchHitResponse"

  schemas:
    fetchHitResponse:
      type: object
      properties:
        attackerId:
          $ref: "./models.yaml#/components/schemas/AttackerId"
        hitPoint:
          $ref: "./models.yaml#/components/schemas/Point"
        hitZone:
          $ref: "./models.yaml#/components/schemas/BodyPart"
        hitAt:
          title: ヒット日時
          type: string
          format: date-time
        target:
          $ref: "./models.yaml#/components/schemas/Target"
      required:
        - attackerId
        - hitPoint
        - hitZone
        - hitAt
        - target
