name: Deploy API Docs

on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash

jobs:
  build-and-deploy-api-doc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
        contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Redoc CLI
        run: npm install -g @redocly/cli

      - name: Generate doc from OpenAPI spec
        run: redocly build-docs ./openapi.yaml -o docs.html

      - name: Deploy to GitHUb Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            publish_dir: .