name: Publish NuGet Package

on:
  push:
    branches:
      - main  # main ブランチへのプッシュをトリガー

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

    # 3. OpenAPI Generator を実行してコードを生成
      - name: Generate code from OpenAPI spec
        run: |
            # 必要に応じて OpenAPI Generator CLI をインストール
            curl -L https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.10.0/openapi-generator-cli-7.10.0.jar -o openapi-generator-cli.jar
            
            # コード生成
            java -jar openapi-generator-cli.jar generate \
                -i ./openapi.yaml \
                -g aspnetcore \
                -o ./generated-server \
                -c ./server.config.json
    
     # 3. バージョン番号をインクリメント
      - name: Increment version number
        run: |
            # 最新のバージョンを取得
            VERSION=$(grep -oP '(?<=<Version>)(.*?)(?=</Version>)' generated-server/src/VitalStrike.Models/*.csproj)
            
            # バージョン番号を「メジャー.マイナー.パッチ」の形式で分割し、パッチ番号をインクリメント
            IFS='.' read -r -a version_parts <<< "$VERSION"
            PATCH=${version_parts[2]}
            PATCH=$((PATCH + 1))

            # 新しいバージョン番号を作成
            NEW_VERSION="${version_parts[0]}.${version_parts[1]}.$PATCH"

      # 4. バージョン番号を更新
      - name: Update version in .csproj
        run: |
          cd generated-server/src/VitalStrike.Models
          # GitVersion からのバージョン番号を利用
          VERSION=${{ steps.gitversion.outputs.semver }}
          sed -i "s/<Version>.*<\/Version>/<Version>${NEW_VERSION}<\/Version>/" *.csproj

      # 5. NuGet パッケージの作成
      - name: Build NuGet Package
        run: |
          cd generated-server/src/VitalStrike.Models
          dotnet pack -c Release

      # 6. NuGet にパッケージをアップロード
      - name: Publish to NuGet
        run: |
          cd generated-server/src/VitalStrike.Models
          pwd
          dotnet nuget push ./bin/Release/*.nupkg \
            -s https://api.nuget.org/v3/index.json \
            -k ${{ secrets.NUGET_API_KEY }}